build-deploy-lambda: build-lambda deploy-lambda
build-lambda:
	./build-lambda.sh
deploy-lambda:
	./redeploy-lambda.sh
run-labmda:
	 ./docker/test-lambda-function.sh
lint:
	gocritic check ./...
	revive ./...
	golint ./...
	go vet ./...
	staticcheck ./...
	golangci-lint run
	goconst ./...
test:
	go test ./...
