port: 8080
lambda:
  packages:
    - name: instructioner
      functions: 
        - snsroute: /:Instruction
    - name: example2
      functions: 
        - route: /add:TestHandler
http:
  packages:
    - name: example2
      functions: 
        - route: /add:TestHandler
        - route: /route2:TestHandler
